[package]
name = "uows-count"
version = "0.1.0"
authors = ["Saadi Save <saadisave@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mongodb]
version = "1"
default-features = false
features = [
    "async-std-runtime"
]

[dependencies.tokio]
version = "0.2"
features = [
    "macros",
    "rt-threaded",
    "fs"
]
