name: Changelog

on:
  push:
    branches:
    - release

jobs:
  changelog:

    runs-on: ubuntu-latest

    steps:
    - name: Changelog Gen
      id: changelog
      uses: loopwerk/conventional-changelog-action@latest
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
