name: Rust

on:
  push:
    branches:
    - main
    - release
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Release build
      run: cargo build --release
    
    - name: Changelog Gen
      id: changelog
      uses: loopwerk/conventional-changelog-action@latest
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
